{{- $baseChartValues := index .Values "cray-service" -}}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "cray-service.name" . }}"
  labels:
    app.kubernetes.io/name: "{{ include "cray-service.name" . }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "cray-service.name" . }}"
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
