apiVersion: v1
description: "Kubernetes resources for config-framework-service"
name: "cray-cfs-api"
home: "scms/config-framework-service"
version: @VERSION@
appVersion: @VERSION@
keywords:
  - config-framework-service
  - cfs-api
  - cfs
sources:
  - "https://stash.us.cray.com/projects/SCMS/repos/config-framework-service/browse"
maintainers:
  - name: rbak
    email: rbak@cray.com
  - name: rkleinman
    email: randy.kleinman@hpe.com
