# Please refer to https://github.com/Cray-HPE/base-charts/tree/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

cray-service:
  type: Deployment
  nameOverride: cray-cfs-api
  serviceAccountName: cray-cfs
  containers:
    cray-cfs-api:
      name: cray-cfs-api
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-cfs
        # tag defaults to chart appVersion
      volumeMounts:
        - name: ca-pubkey
          mountPath: /etc/cray/ca
          readOnly: true
      env:
        - name: GIT_SSL_CAINFO
          value: /etc/cray/ca/certificate_authority.crt
        - name: VCS_USERNAME
          valueFrom:
            secretKeyRef:
              name: vcs-user-credentials
              key: vcs_username
        - name: VCS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vcs-user-credentials
              key: vcs_password
      ports:
        - name: http
          containerPort: 9000
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /healthz
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
      livenessProbe:
        httpGet:
          path: /healthz
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 20
      resources:
        requests:
          memory: "100Mi"
          cpu: "150m"
        limits:
          memory: "250Mi"
          cpu: "500m"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - cray-cfs-api
  ingress:
    ui: false
    enabled: true
    prefix: /apis/cfs/
    uri: /
  volumes:
    - name: ca-pubkey
      configMap:
        defaultMode: 420
        items:
          - key: certificate_authority.crt
            path: certificate_authority.crt
        name: cray-configmap-ca-public-key

database:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/redis
    tag: 5.0-alpine
